export const sampleReviewData = {
  reviewCount: 2,
  cursorId: 102,
  reviews: [
    {
      id: 101,
      memberId: 2001,
      nickname: "멍멍이사랑해",
      memberBreed: "푸들",
      disease: "피부병",
      age: 3,
      hospitalId: 10,
      hospitalName: "행복한동물병원",
      vistitedAt: "2025-04-01",
      hospitalAddress: "서울특별시 강남구 도곡로 123",
      content: "친절하고 꼼꼼하게 진료해주셨어요. 재방문의사 100%",
      reviewSummary: "친절하고 꼼꼼한 진료",
      images: ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      symptoms: ["기침", "호흡곤란"],
      diseases: ["심장병"],
      animal: "강아지",
      gender: "여아",
      breed: "푸들",
      weight: 3.5,
      visitPurpose: "정기검진",
      goodReviews: [
        { id: 1, name: "친절해요" },
        { id: 2, name: "설명이 자세해요" },
      ],
      badReviews: [{ id: 1, name: "기다림이 길어요" }],
    },
    {
      id: 102,
      memberId: 2002,
      nickname: "고양이집사",
      memberBreed: "페르시안",
      disease: "요로결석",
      age: 3,
      hospitalId: 11,
      hospitalName: "사랑동물병원",
      vistitedAt: "2025-03-15",
      hospitalAddress: "서울특별시 서초구 서초대로 456",
      content: "24시간 운영이라 긴급한 상황에 도움이 되었어요.",
      reviewSummary: "긴급 상황에 빠른 대응",
      images: [
        "https://example.com/image1.jpg",
        "https://example.com/image2.jpg",
        "https://example.com/image1.jpg",
        "https://example.com/image2.jpg",
      ],
      symptoms: ["소변보기 힘들어함", "배가 아파보임"],
      diseases: ["요로결석"],
      animal: "고양이",
      gender: "남아",
      breed: "페르시안",
      weight: 4.2,
      visitPurpose: "응급처치",
      goodReviews: [
        { id: 1, name: "24시간 운영" },
        { id: 2, name: "응급처치가 빨라요" },
      ],
      badReviews: [{ id: 1, name: "비용이 비싸요" }],
    },
  ],
} as const;
