export const ANIMAL = {
  data: {
    breeds: [
      { id: 1, name: "포메라니안" },
      { id: 2, name: "말티푸" },
      { id: 3, name: "말티팡" },
      { id: 4, name: "말티즈" },
      { id: 5, name: "말티자" },
      { id: 6, name: "푸들" },
      { id: 7, name: "치와와" },
      { id: 8, name: "래브라도 리트리버" },
      { id: 9, name: "샴푸" },
      { id: 10, name: "시추" },
      { id: 11, name: "페르시안" },
      { id: 12, name: "샴" },
      { id: 13, name: "러시안 블루" },
      { id: 14, name: "노르웨이 숲" },
      { id: 15, name: "스코티시 폴드" },
      { id: 16, name: "벵갈" },
      { id: 17, name: "브리티시 쇼트헤어" },
      { id: 18, name: "아메리칸 쇼트헤어" },
      { id: 19, name: "레그돌" },
      { id: 20, name: "메인쿤" },
    ],
  },
};
