name: Synchronize develop to forked repos
on:
  push:
    branches:
      - develop

jobs:
  sync:
    name: Sync forked repo
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORKED_DEV_SERVER_TOKEN }}
          fetch-depth: 0
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://yarimu:${{ secrets.FORKED_DEV_SERVER_TOKEN }}@github.com/yarimu/cocos-frontend
          git config user.name yarimu
          git config user.email ${{ secrets.YARIMU_EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo develop

      - name: Clean up
        run: |
          git remote remove forked-repo
